# Generated by Django 3.2.12 on 2022-03-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Mərtəbə adı')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField(verbose_name='Xarici dil')),
            ],
            options={
                'verbose_name': 'Xarici dil',
                'verbose_name_plural': 'Xarici dili',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField(verbose_name='Cins')),
            ],
            options={
                'verbose_name': 'Cins',
                'verbose_name_plural': 'Cinsi',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField(verbose_name='Qrup')),
            ],
            options={
                'verbose_name': 'Qrup',
                'verbose_name_plural': 'Qrupu',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField(verbose_name='Bölmə')),
            ],
            options={
                'verbose_name': 'Bölmə',
                'verbose_name_plural': 'Bölməni',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Məntəqə adı')),
                ('address', models.TextField(verbose_name='Məntəqə ünvanı')),
            ],
            options={
                'verbose_name': 'Məntəqə',
                'verbose_name_plural': 'Məntəqəni',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveIntegerField(verbose_name='Sinif')),
            ],
            options={
                'verbose_name': 'Sinif',
                'verbose_name_plural': 'Sinifi',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=60, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Şagird',
                'verbose_name_plural': 'Şagirdi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='')),
                ('number_of_place', models.PositiveIntegerField(verbose_name='Yer sayı')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.gender', verbose_name='Cinsi')),
            ],
            options={
                'verbose_name': 'Otaq',
                'verbose_name_plural': 'Otağı',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='İmtahan')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.station', verbose_name='Məntəqə')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahanı',
                'ordering': ['title'],
            },
        ),
    ]
