# Generated by Django 3.2.12 on 2022-03-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flor',
            options={'ordering': ['name'], 'verbose_name': 'Mərtəbə', 'verbose_name_plural': 'Mərtəbəni'},
        ),
        migrations.AddField(
            model_name='station',
            name='flor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.flor', verbose_name='Məntəqə'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Otaq adı'),
        ),
    ]
