# Generated by Django 3.2.12 on 2022-03-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20220303_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='station',
        ),
        migrations.RemoveField(
            model_name='room',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='station',
            name='flor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Flor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
