# Generated by Django 3.2.12 on 2022-03-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20220305_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='İmtahan adı')),
                ('exam_date', models.DateField(verbose_name='')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahan',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='foreignlanguage',
            options={'ordering': ['-title'], 'verbose_name': 'Xarici dil', 'verbose_name_plural': 'Xarici dil'},
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=60, verbose_name='Soyad')),
                ('phone', models.IntegerField(verbose_name='Telefon nömrəsi')),
                ('school', models.CharField(max_length=60, verbose_name='Məktəb')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Qeydiyyat tarixi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='İmtahan')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.gender', verbose_name='Cins')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.group', verbose_name='Qrup')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.foreignlanguage', verbose_name='Xarici dil')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.section', verbose_name='Bölmə')),
                ('stclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.stclass', verbose_name='Sinif')),
            ],
            options={
                'verbose_name': 'Şagird',
                'verbose_name_plural': 'Şagird',
                'ordering': ['-create_at'],
            },
        ),
    ]
