# Generated by Django 3.2.12 on 2022-03-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20220305_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='')),
                ('address', models.TextField(verbose_name='Ünvan')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='İmtahan')),
            ],
            options={
                'verbose_name': 'İmtahan məntəqəsi',
                'verbose_name_plural': 'İmtahan məntəqəsi',
                'ordering': ['name'],
            },
        ),
    ]
