# Generated by Django 3.2.12 on 2022-03-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(verbose_name='İmtahan tarixi'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Məntəqə adı'),
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mərtəbə adı')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.location', verbose_name='Məntəqə')),
            ],
            options={
                'verbose_name': 'Mərtəbə',
                'verbose_name_plural': 'Mərtəbə',
                'ordering': ['name'],
            },
        ),
    ]
