# Generated by Django 3.2.12 on 2022-03-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20220305_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Otaq adı')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.floor', verbose_name='Mərtəbə')),
            ],
            options={
                'verbose_name': 'Otaq',
                'verbose_name_plural': 'Otaq',
                'ordering': ['name'],
            },
        ),
    ]
